#数据库配置
database:
  user: "root"
  password: "root"
  host: "localhost"
  port: 3306
  name: "cloudhivegallery"
tcos:
    bucketName: "cloudhivegallery-1348386678"
    region: "ap-guangzhou"
    host: "https://cloudhivegallery-1348386678.cos.ap-guangzhou.myqcloud.com"
rds:
    host: "localhost"
    port: 6379
    password: "chg"
aliYunAi:
  apiKey: "sk-6daaa1e5d9b3425f975ec6a7814e6b8b"