// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/file/test/download": {
            "get": {
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "file"
                ],
                "summary": "测试文件下载接口「管理员」",
                "parameters": [
                    {
                        "type": "string",
                        "description": "文件存储在 COS 的 KEY",
                        "name": "key",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回文件流",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "下载失败，详情见响应中的 code",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    }
                }
            }
        },
        "/v1/file/test/upload": {
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "file"
                ],
                "summary": "测试文件上传接口「管理员」",
                "parameters": [
                    {
                        "type": "file",
                        "description": "文件",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "响应文件存储在COS的KEY",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "更新失败，详情见响应中的code",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    }
                }
            }
        },
        "/v1/picture/delete": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "picture"
                ],
                "summary": "根据ID软删除图片",
                "parameters": [
                    {
                        "description": "图片的ID",
                        "name": "id",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/common.DeleteRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "删除成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "boolean"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "删除失败，详情见响应中的code",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    }
                }
            }
        },
        "/v1/picture/edit": {
            "post": {
                "description": "若图片不存在，则返回false",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "picture"
                ],
                "summary": "更新图片",
                "parameters": [
                    {
                        "description": "需要更新的图片信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/picture.PictureEditRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "boolean"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "更新失败，详情见响应中的code",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    }
                }
            }
        },
        "/v1/picture/get": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "picture"
                ],
                "summary": "根据ID获取图片「管理员」",
                "parameters": [
                    {
                        "type": "string",
                        "description": "图片的ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/entity.Picture"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "获取失败，详情见响应中的code",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    }
                }
            }
        },
        "/v1/picture/get/vo": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "picture"
                ],
                "summary": "根据ID获取脱敏的图片",
                "parameters": [
                    {
                        "type": "string",
                        "description": "图片的ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/picture.PictureVO"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "获取失败，详情见响应中的code",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    }
                }
            }
        },
        "/v1/picture/list/page": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "picture"
                ],
                "summary": "分页获取一系列图片信息「管理员」",
                "parameters": [
                    {
                        "description": "需要查询的页数、以及图片关键信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/picture.PictureQueryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "查询成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/picture.ListPictureResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "更新失败，详情见响应中的code",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    }
                }
            }
        },
        "/v1/picture/list/page/vo": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "picture"
                ],
                "summary": "分页获取一系列图片信息",
                "parameters": [
                    {
                        "description": "需要查询的页数、以及图片关键信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/picture.PictureQueryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "查询成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/picture.ListPictureVOResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "更新失败，详情见响应中的code",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    }
                }
            }
        },
        "/v1/picture/review": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "picture"
                ],
                "summary": "执行图片审核「管理员」",
                "parameters": [
                    {
                        "description": "审核图片所需信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/picture.PictureReviewRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "审核更新成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "boolean"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "更新失败，详情见响应中的code",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    }
                }
            }
        },
        "/v1/picture/tag_category": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "picture"
                ],
                "summary": "获取图片的标签和分类（固定）",
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/picture.PictureTagCategory"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "更新失败，详情见响应中的code",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    }
                }
            }
        },
        "/v1/picture/update": {
            "post": {
                "description": "若图片不存在，则返回false",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "picture"
                ],
                "summary": "更新图片",
                "parameters": [
                    {
                        "description": "需要更新的图片信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/picture.PictureUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "boolean"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "更新失败，详情见响应中的code",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    }
                }
            }
        },
        "/v1/picture/upload": {
            "post": {
                "description": "根据是否存在ID来上传图片或者修改图片信息，返回图片信息视图",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "picture"
                ],
                "summary": "上传图片接口「需要登录校验」",
                "parameters": [
                    {
                        "type": "file",
                        "description": "图片",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "图片的ID，非必需",
                        "name": "id",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "上传成功，返回图片信息视图",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/picture.PictureVO"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "更新失败，详情见响应中的code",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    }
                }
            }
        },
        "/v1/picture/upload/batch": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "picture"
                ],
                "summary": "批量抓取图片「管理员」",
                "parameters": [
                    {
                        "description": "图片的关键词",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/picture.PictureUploadByBatchRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回抓取图片数量",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "integer"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "更新失败，详情见响应中的code",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    }
                }
            }
        },
        "/v1/picture/upload/url": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "picture"
                ],
                "summary": "根据URL上传图片接口「需要登录校验」",
                "parameters": [
                    {
                        "description": "图片URL",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/picture.PictureUploadRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "上传成功，返回图片信息视图",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/picture.PictureVO"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "更新失败，详情见响应中的code",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    }
                }
            }
        },
        "/v1/user/add": {
            "post": {
                "description": "默认密码为12345678",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "创建一个用户「管理员」",
                "parameters": [
                    {
                        "description": "用户添加申请参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.UserAddRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "添加成功，返回添加用户的ID",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "添加失败，详情见响应中的code",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    }
                }
            }
        },
        "/v1/user/delete": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "根据ID软删除用户「管理员」",
                "parameters": [
                    {
                        "description": "用户的ID",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/common.DeleteRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "删除成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "boolean"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "删除失败，详情见响应中的code",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    }
                }
            }
        },
        "/v1/user/get": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "根据ID获取用户「管理员」",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户的ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "查询成功，返回用户的所有信息",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/entity.User"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "查询失败，详情见响应中的code",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    }
                }
            }
        },
        "/v1/user/get/login": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "获取登录的用户信息",
                "responses": {
                    "200": {
                        "description": "获取用户视图成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/user.UserLoginVO"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "获取失败，详情见响应中的code",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    }
                }
            }
        },
        "/v1/user/get/vo": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "根据ID获取简略信息用户",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户的ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "查询成功，返回用户的脱敏信息",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/user.UserVO"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "查询失败，详情见响应中的code",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    }
                }
            }
        },
        "/v1/user/list/page/vo": {
            "post": {
                "description": "根据用户关键信息进行模糊查询",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "分页获取一系列用户信息「管理员」",
                "parameters": [
                    {
                        "description": "需要查询的页数、以及用户关键信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.UserQueryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "查询成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/user.ListUserVOResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "更新失败，详情见响应中的code",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    }
                }
            }
        },
        "/v1/user/login": {
            "post": {
                "description": "根据账号密码进行登录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "用户登录请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.UserLoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "登录成功，返回用户视图",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/user.UserLoginVO"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "登录失败，详情见响应中的code",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    }
                }
            }
        },
        "/v1/user/logout": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "执行用户注销（退出）",
                "responses": {
                    "200": {
                        "description": "退出成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "boolean"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "注册失败，详情见响应中的code",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    }
                }
            }
        },
        "/v1/user/register": {
            "post": {
                "description": "根据账号密码进行注册",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "注册用户",
                "parameters": [
                    {
                        "description": "用户请求注册参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.UserRegsiterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "注册成功，返回注册用户的ID",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "注册失败，详情见响应中的code",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    }
                }
            }
        },
        "/v1/user/update": {
            "post": {
                "description": "若用户不存在，则返回失败",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "更新用户信息「管理员」",
                "parameters": [
                    {
                        "description": "需要更新的用户信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.UserUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "boolean"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "更新失败，详情见响应中的code",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "common.DeleteRequest": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "id": {
                    "type": "string",
                    "example": ""
                }
            }
        },
        "common.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "type": "object"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "entity.Picture": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "createTime": {
                    "type": "string"
                },
                "editTime": {
                    "type": "string"
                },
                "id": {
                    "type": "string",
                    "example": ""
                },
                "introduction": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "picFormat": {
                    "type": "string"
                },
                "picHeight": {
                    "type": "integer"
                },
                "picScale": {
                    "type": "number"
                },
                "picSize": {
                    "type": "integer"
                },
                "picWidth": {
                    "type": "integer"
                },
                "reviewMessage": {
                    "type": "string"
                },
                "reviewStatus": {
                    "type": "integer"
                },
                "reviewTime": {
                    "type": "string"
                },
                "reviewerId": {
                    "type": "string",
                    "example": ""
                },
                "tags": {
                    "description": "存储的格式：[\"golang\",\"java\",\"c++\"]",
                    "type": "string"
                },
                "updateTime": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                },
                "userId": {
                    "type": "string",
                    "example": ""
                }
            }
        },
        "entity.User": {
            "type": "object",
            "properties": {
                "createTime": {
                    "type": "string"
                },
                "editTime": {
                    "type": "string"
                },
                "id": {
                    "type": "string",
                    "example": ""
                },
                "updateTime": {
                    "type": "string"
                },
                "userAccount": {
                    "type": "string"
                },
                "userAvatar": {
                    "type": "string"
                },
                "userName": {
                    "type": "string"
                },
                "userPassword": {
                    "type": "string"
                },
                "userProfile": {
                    "type": "string"
                },
                "userRole": {
                    "type": "string"
                }
            }
        },
        "picture.ListPictureResponse": {
            "type": "object",
            "properties": {
                "current": {
                    "description": "当前页数",
                    "type": "integer"
                },
                "pages": {
                    "description": "总页数",
                    "type": "integer"
                },
                "records": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.Picture"
                    }
                },
                "size": {
                    "description": "页面大小",
                    "type": "integer"
                },
                "total": {
                    "description": "总记录数",
                    "type": "integer"
                }
            }
        },
        "picture.ListPictureVOResponse": {
            "type": "object",
            "properties": {
                "current": {
                    "description": "当前页数",
                    "type": "integer"
                },
                "pages": {
                    "description": "总页数",
                    "type": "integer"
                },
                "records": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/picture.PictureVO"
                    }
                },
                "size": {
                    "description": "页面大小",
                    "type": "integer"
                },
                "total": {
                    "description": "总记录数",
                    "type": "integer"
                }
            }
        },
        "picture.PictureEditRequest": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "id": {
                    "type": "string",
                    "example": ""
                },
                "introduction": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "picture.PictureQueryRequest": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "current": {
                    "description": "当前页数",
                    "type": "integer"
                },
                "id": {
                    "description": "图片ID",
                    "type": "string",
                    "example": ""
                },
                "introduction": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "pageSize": {
                    "description": "页面大小",
                    "type": "integer"
                },
                "picFormat": {
                    "type": "string"
                },
                "picHeight": {
                    "type": "integer"
                },
                "picScale": {
                    "type": "number"
                },
                "picSize": {
                    "type": "integer"
                },
                "picWidth": {
                    "type": "integer"
                },
                "reviewMessage": {
                    "type": "string"
                },
                "reviewStatus": {
                    "description": "新增审核字段",
                    "type": "string",
                    "example": ""
                },
                "reviewerId": {
                    "description": "审核人ID",
                    "type": "string",
                    "example": ""
                },
                "searchText": {
                    "description": "搜索词",
                    "type": "string"
                },
                "sortField": {
                    "description": "排序字段",
                    "type": "string"
                },
                "sortOrder": {
                    "description": "排序顺序（默认升序）",
                    "type": "string"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "userId": {
                    "description": "图片上传人信息",
                    "type": "string",
                    "example": ""
                }
            }
        },
        "picture.PictureReviewRequest": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "图片ID",
                    "type": "string",
                    "example": ""
                },
                "reviewMessage": {
                    "description": "审核信息",
                    "type": "string"
                },
                "reviewStatus": {
                    "description": "审核状态",
                    "type": "string",
                    "example": ""
                }
            }
        },
        "picture.PictureTagCategory": {
            "type": "object",
            "properties": {
                "categoryList": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "tagList": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "picture.PictureUpdateRequest": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "id": {
                    "type": "string",
                    "example": ""
                },
                "introduction": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "picture.PictureUploadByBatchRequest": {
            "type": "object",
            "properties": {
                "count": {
                    "description": "图片数量",
                    "type": "integer"
                },
                "namePrefix": {
                    "description": "图片名称前缀，默认为SearchText",
                    "type": "string"
                },
                "searchText": {
                    "description": "搜索词",
                    "type": "string"
                }
            }
        },
        "picture.PictureUploadRequest": {
            "type": "object",
            "properties": {
                "fileUrl": {
                    "description": "图片地址",
                    "type": "string"
                },
                "id": {
                    "description": "图片ID",
                    "type": "string",
                    "example": ""
                },
                "picName": {
                    "description": "图片名称",
                    "type": "string"
                }
            }
        },
        "picture.PictureVO": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "createTime": {
                    "type": "string"
                },
                "editTime": {
                    "type": "string"
                },
                "id": {
                    "type": "string",
                    "example": "0"
                },
                "introduction": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "picFormat": {
                    "type": "string"
                },
                "picHeight": {
                    "type": "integer"
                },
                "picScale": {
                    "type": "number"
                },
                "picSize": {
                    "type": "integer"
                },
                "picWidth": {
                    "type": "integer"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "updateTime": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/user.UserVO"
                },
                "userId": {
                    "type": "string",
                    "example": "0"
                }
            }
        },
        "user.ListUserVOResponse": {
            "type": "object",
            "properties": {
                "current": {
                    "description": "当前页数",
                    "type": "integer"
                },
                "pages": {
                    "description": "总页数",
                    "type": "integer"
                },
                "records": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/user.UserVO"
                    }
                },
                "size": {
                    "description": "页面大小",
                    "type": "integer"
                },
                "total": {
                    "description": "总记录数",
                    "type": "integer"
                }
            }
        },
        "user.UserAddRequest": {
            "type": "object",
            "required": [
                "userAccount"
            ],
            "properties": {
                "userAccount": {
                    "description": "用户账号",
                    "type": "string"
                },
                "userAvatar": {
                    "description": "用户头像",
                    "type": "string"
                },
                "userName": {
                    "description": "用户昵称",
                    "type": "string"
                },
                "userProfile": {
                    "description": "用户简介",
                    "type": "string"
                },
                "userRole": {
                    "description": "用户权限",
                    "type": "string"
                }
            }
        },
        "user.UserLoginRequest": {
            "type": "object",
            "required": [
                "userAccount",
                "userPassword"
            ],
            "properties": {
                "userAccount": {
                    "type": "string"
                },
                "userPassword": {
                    "type": "string"
                }
            }
        },
        "user.UserLoginVO": {
            "type": "object",
            "properties": {
                "createTime": {
                    "type": "string"
                },
                "editTime": {
                    "type": "string"
                },
                "id": {
                    "type": "string",
                    "example": ""
                },
                "updateTime": {
                    "type": "string"
                },
                "userAccount": {
                    "type": "string"
                },
                "userAvatar": {
                    "type": "string"
                },
                "userName": {
                    "type": "string"
                },
                "userProfile": {
                    "type": "string"
                },
                "userRole": {
                    "type": "string"
                }
            }
        },
        "user.UserQueryRequest": {
            "type": "object",
            "properties": {
                "current": {
                    "description": "当前页数",
                    "type": "integer"
                },
                "id": {
                    "description": "用户ID",
                    "type": "string",
                    "example": ""
                },
                "pageSize": {
                    "description": "页面大小",
                    "type": "integer"
                },
                "sortField": {
                    "description": "排序字段",
                    "type": "string"
                },
                "sortOrder": {
                    "description": "排序顺序（默认升序）",
                    "type": "string"
                },
                "userAccount": {
                    "description": "用户账号",
                    "type": "string"
                },
                "userName": {
                    "description": "用户昵称",
                    "type": "string"
                },
                "userProfile": {
                    "description": "用户简介",
                    "type": "string"
                },
                "userRole": {
                    "description": "用户权限",
                    "type": "string"
                }
            }
        },
        "user.UserRegsiterRequest": {
            "type": "object",
            "required": [
                "checkPassword",
                "userAccount",
                "userPassword"
            ],
            "properties": {
                "checkPassword": {
                    "type": "string"
                },
                "userAccount": {
                    "type": "string"
                },
                "userPassword": {
                    "type": "string"
                }
            }
        },
        "user.UserUpdateRequest": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "用户ID",
                    "type": "string",
                    "example": ""
                },
                "userAvatar": {
                    "description": "用户头像",
                    "type": "string"
                },
                "userName": {
                    "description": "用户昵称",
                    "type": "string"
                },
                "userProfile": {
                    "description": "用户简介",
                    "type": "string"
                },
                "userRole": {
                    "description": "用户权限",
                    "type": "string"
                }
            }
        },
        "user.UserVO": {
            "type": "object",
            "properties": {
                "createTime": {
                    "type": "string"
                },
                "id": {
                    "type": "string",
                    "example": ""
                },
                "userAccount": {
                    "type": "string"
                },
                "userAvatar": {
                    "type": "string"
                },
                "userName": {
                    "type": "string"
                },
                "userProfile": {
                    "type": "string"
                },
                "userRole": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BasicAuth": {
            "type": "basic"
        }
    },
    "externalDocs": {
        "description": "OpenAPI",
        "url": "https://swagger.io/resources/open-api/"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "CloudHiveGallery",
	Description:      "云巢画廊接口文档",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
