definitions:
  common.Response:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
  request.UserRegsiterRequest:
    properties:
      checkPassword:
        type: string
      userAccount:
        type: string
      userPassword:
        type: string
    required:
    - checkPassword
    - userAccount
    - userPassword
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: 云巢画廊接口文档
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: CloudHiveGallery
  version: "1.0"
paths:
  /v1/user/register:
    post:
      consumes:
      - application/json
      description: 根据账号密码进行注册
      parameters:
      - description: 用户请求注册参数
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.UserRegsiterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 注册成功，返回注册用户的ID
          schema:
            allOf:
            - $ref: '#/definitions/common.Response'
            - properties:
                data:
                  type: string
              type: object
        "400":
          description: 注册失败，详情见响应中的code
          schema:
            $ref: '#/definitions/common.Response'
      summary: 注册用户
      tags:
      - user
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
